// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC1() {
    driver.Navigate().GoToUrl("https://testpages.herokuapp.com/styled/basic-html-form-test.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys("TestUser");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("testpassword");
    driver.FindElement(By.Name("comments")).Click();
    driver.FindElement(By.Name("comments")).SendKeys("Comments...test comment\\ncomment 2");
    driver.FindElement(By.CssSelector("tr:nth-child(5) input:nth-child(3)")).Click();
    driver.FindElement(By.Name("checkboxes[]")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(5) input:nth-child(4)")).Click();
    driver.FindElement(By.Name("radioval")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(6) input:nth-child(4)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(6) input:nth-child(3)")).Click();
    {
      var dropdown = driver.FindElement(By.Name("multipleselect[]"));
      dropdown.FindElement(By.XPath("//option[. = 'Selection Item 3']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Name("multipleselect[]"));
      dropdown.FindElement(By.XPath("//option[. = 'Selection Item 4']")).Click();
    }
    driver.FindElement(By.Name("dropdown")).Click();
    {
      var dropdown = driver.FindElement(By.Name("dropdown"));
      dropdown.FindElement(By.XPath("//option[. = 'Drop Down Item 5']")).Click();
    }
    driver.FindElement(By.CssSelector(".styled-click-button:nth-child(2)")).Click();
  }
}
